### ISSUE TITLE
Add `p` tag to stimulus in the introduction trial

### ISSUE THREAD

**Issue by RobertGemmaJr** [brown-ccv/neuro-task-starter#487]
What other trials are missing an html tag?

**Comment by RobertGemmaJr** [comment]
@YUUU23 The introduction trial can be found at `src/experiment/introduction`. Note the `p` function in `src/lib/markup/tags`.

These functions were added to make the creation of HTML strings easier, which is a unique challenge of working with jsPsych. Do some digging to see how jsPsych uses the HTML strings and what those tag functions do. Happy to answer any questions! The issue itself is just that the introduction trial is _not_ using the `p` function. Can you see what changes when you add it?

**Comment by YUUU23** [comment]
@RobertGemmaJr 

I noticed that the original introduction stimulus uses `h1` instead of `p`, which makes the introduction text a large heading instead of a regular text, assuming the latter is what is preferred. I've created a [PR](https://github.com/brown-ccv/honeycomb/pull/493) to refactor this; if you can take a look when you have time that would be really appreciated! 

Thanks!
